use Store;
go

insert into Brands(Brand) values 
						('Nike'),
						('New balance'),
						('Under Armour'),
						('Puma'),
						('Converse'),
						('Columnbia'),
						('Asics'),
						('Vans'),
						('Tommy Hilfiger'),
						('Fila'),
						('Fred Perry'),
						('Stone Island'),
						('Lacoste'),
						('S’Oliver'),
						('Asos'),
						('Gucci'),
						('Versace'),
						('Burberry'),
						('Louis Vuitton'),
						('Prada'),
						('Dolce & Gabbana'),
						('Chanel'),
						('Giorgio Armani'),
						('Guess'),
						('Zara'),
						('H&M'),
						('GAP'),
						('Calvin Klein'),
						('Tom Tailor'),
						('Givenchy'),
						('Champion'),
						('Crocs'),
						('DC'),
						('Dior'),
						('Diesel'),
						('Obey'),
						('BOSS');


insert into Categories(Category) values 
						('Underwear'),
						('Casual clothes'),
						('Sports clothes'),
						('Accessories'),
						('Caps and Hats'),
						('Sweaters'),
						('Pants/Trousers'),
						('Shorts'),
						('Socks'),
						('Coats'),
						('Jackets and Hoodies'),
						('Robes and Cloaks'),
						('Windbreaker'),
						('Gloves'),
						('Footwear'),
						('Jeans'),
						('Polos'),
						('Skirt'),
						('Sundress'),
						('T-Shirt'),
						('Bermuda Shorts'),
						('Business Suits'),
						('Cardigans'),
						('Cargo Shorts'),
						('Leather Jacket'),
						('Leggings'),
						('Miniskirt'),
						('Pajamas'),
						('Parkas'),
						('Rugby Shirts'),
						('Scarfs'),
						('Skating Dress'),
						('Slacks'),
						('Soccer Shirt'),
						('Trench Coats'),
						('Turtlenecks'),
						('Wet Suit'),
						('Wear a Lab Coats'),
						('Yoga Pants'),
						('Wedding Dress');


insert into Sizes(Size) values 
						('XXS'),
						('XS'),
						('S'),
						('M'),
						('L'),
						('XL'),
						('XXL'),
						('XXXL');